#pragma once

void GetBasicArrays(std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & aa_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & ab_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & ac_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & bb_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & bc_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & cc_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_aa_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_ab_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_ac_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_bb_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_bc_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_cc_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & aa_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & ab_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & ac_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & bb_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & bc_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & cc_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_aa_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_ab_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_ac_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_bb_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_bc_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_cc_2);

void WriteBasicArraysFile(std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & aa_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & ab_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & ac_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & bb_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & bc_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & cc_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_aa_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_ab_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_ac_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_bb_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_bc_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_cc_1,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & aa_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & ab_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & ac_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & bb_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & bc_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & cc_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_aa_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_ab_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_ac_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_bb_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_bc_2,
	std::vector<std::vector<std::vector<std::vector<std::complex<double>>>>> & overline_cc_2);
